project:
  type: website

website:
  title: "Jonathan Chandra"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: bio.qmd
        text: Bio
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: students.qmd
        text: Supervision
  page-footer:
    center: "© Jonathan Chandra"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    smooth-scroll: true

execute:
  freeze: auto
